/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rumahlaundry.master;

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rumahlaundry.Home;
import rumahlaundry.Login;
import rumahlaundry.master.setting.ChangePassword;
import rumahlaundry.master.setting.Profile;
import rumahlaundry.report.ReportCustomer;
import rumahlaundry.report.ReportHistoryTransaction;
import rumahlaundry.report.ReportTransaction;
import rumahlaundry.transaction.TransactionClose;
import rumahlaundry.transaction.TransactionOrder;
import rumahlaundry.transaction.TransactionPayment;
import rumahlaundry.transaction.TransactionService;
import rumahlaundry.util.MyConnection;
import rumahlaundry.util.MyHelper;

/**
 *
 * @author lukman.arizal
 */
public class MasterPackage extends javax.swing.JFrame {

    private final Connection connection = new MyConnection().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form Package
     */
    public MasterPackage() {
        initComponents();
        dataTable();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
    }
    
    private void dataTable() {
        Object[] Baris = {"Kode", "Nama", "Harga", "Keterangan"};
        tabmode = new DefaultTableModel(null, Baris);
        tablePaket.setModel(tabmode);
        try {
            Statement stat = connection.createStatement();
            String sql = "SELECT * FROM MASTER_PACKAGE ORDER BY PACKAGE_ID";
            ResultSet result = stat.executeQuery(sql);
            if (result != null) {
                while (result.next()) {
                    String kode = result.getString("package_id");
                    String nama = result.getString("package_name");
                    String kontak = result.getString("package_price");
                    String alamat = result.getString("package_description");
                    String[] data = {kode, nama, kontak, alamat};
                    tabmode.addRow(data);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Data Paket tidak ditemukan");
                doReset();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void doReset() {
        textKodePaket.setText("");
        textNamaPaket.setText("");
        textHargaPaket.setText("");
        textAreaKeterangan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelKodePaket = new javax.swing.JLabel();
        textKodePaket = new javax.swing.JTextField();
        jLabelNamaPaket = new javax.swing.JLabel();
        textNamaPaket = new javax.swing.JTextField();
        jLabelHargaPaket = new javax.swing.JLabel();
        textHargaPaket = new javax.swing.JTextField();
        jLabelKeterangan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaKeterangan = new javax.swing.JTextArea();
        buttonSave = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelKataKunci = new javax.swing.JLabel();
        textKataKunci = new javax.swing.JTextField();
        buttonCari = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePaket = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTransaksi = new javax.swing.JMenu();
        jMenuItemTransaksiBaru = new javax.swing.JMenuItem();
        jMenuItemPembayaranTransaksi = new javax.swing.JMenuItem();
        jMenuItemTransaksiLayanan = new javax.swing.JMenuItem();
        jMenuItemTransaksiSelesai = new javax.swing.JMenuItem();
        jMenuLaporan = new javax.swing.JMenu();
        jMenuItemLaporanPelanggan = new javax.swing.JMenuItem();
        jMenuItemLaporanTransaksi = new javax.swing.JMenuItem();
        jMenuItemRiwayatTransasiPelanggan = new javax.swing.JMenuItem();
        jMenuMaster = new javax.swing.JMenu();
        jMenuItemDataKaryawan = new javax.swing.JMenuItem();
        jMenuItemDataPelanggan = new javax.swing.JMenuItem();
        jMenuItemDataPaket = new javax.swing.JMenuItem();
        jMenuItemDataLayanan = new javax.swing.JMenuItem();
        jMenuPengaturan = new javax.swing.JMenu();
        jMenuItemProfile = new javax.swing.JMenuItem();
        jMenuItemGantiPassword = new javax.swing.JMenuItem();
        jMenuItemKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data Paket");

        jLabelKodePaket.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabelKodePaket.setText("Kode Paket");

        textKodePaket.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        textKodePaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKodePaketActionPerformed(evt);
            }
        });

        jLabelNamaPaket.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabelNamaPaket.setText("Nama Paket");

        textNamaPaket.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        textNamaPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaPaketActionPerformed(evt);
            }
        });

        jLabelHargaPaket.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabelHargaPaket.setText("Harga Paket");

        textHargaPaket.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        textHargaPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHargaPaketActionPerformed(evt);
            }
        });

        jLabelKeterangan.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabelKeterangan.setText("Keterangan");

        textAreaKeterangan.setColumns(20);
        textAreaKeterangan.setRows(5);
        jScrollPane1.setViewportView(textAreaKeterangan);

        buttonSave.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        buttonSave.setText("SAVE");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        buttonEdit.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        buttonEdit.setText("EDIT");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonDelete.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        buttonDelete.setText("DELETE");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonReset.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        buttonReset.setText("CLEAR");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHargaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textHargaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(buttonSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonReset)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelKodePaket, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(textKodePaket, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(textNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKodePaket)
                    .addComponent(textKodePaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNamaPaket)
                    .addComponent(textNamaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHargaPaket)
                    .addComponent(textHargaPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKeterangan)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSave)
                    .addComponent(buttonEdit)
                    .addComponent(buttonDelete)
                    .addComponent(buttonReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelKataKunci.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        labelKataKunci.setText("Kata Kunci");

        textKataKunci.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        textKataKunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKataKunciActionPerformed(evt);
            }
        });

        buttonCari.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        buttonCari.setText("Cari");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelKataKunci, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textKataKunci, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCari)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKataKunci)
                    .addComponent(textKataKunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCari))
                .addContainerGap())
        );

        tablePaket.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        tablePaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Harga", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePaketMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablePaket);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(64, 30));

        jMenuTransaksi.setText("Transaksi");
        jMenuTransaksi.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N

        jMenuItemTransaksiBaru.setText("Transaksi Baru");
        jMenuItemTransaksiBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransaksiBaruActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemTransaksiBaru);

        jMenuItemPembayaranTransaksi.setText("Pembayaran Transaksi");
        jMenuItemPembayaranTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPembayaranTransaksiActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemPembayaranTransaksi);

        jMenuItemTransaksiLayanan.setText("Transaksi Layanan");
        jMenuItemTransaksiLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransaksiLayananActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemTransaksiLayanan);

        jMenuItemTransaksiSelesai.setText("Transaksi Selesai");
        jMenuItemTransaksiSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTransaksiSelesaiActionPerformed(evt);
            }
        });
        jMenuTransaksi.add(jMenuItemTransaksiSelesai);

        jMenuBar1.add(jMenuTransaksi);

        jMenuLaporan.setText("Laporan");
        jMenuLaporan.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N

        jMenuItemLaporanPelanggan.setText("Laporan Pelanggan");
        jMenuItemLaporanPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLaporanPelangganActionPerformed(evt);
            }
        });
        jMenuLaporan.add(jMenuItemLaporanPelanggan);

        jMenuItemLaporanTransaksi.setText("Laporan Transaksi");
        jMenuItemLaporanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLaporanTransaksiActionPerformed(evt);
            }
        });
        jMenuLaporan.add(jMenuItemLaporanTransaksi);

        jMenuItemRiwayatTransasiPelanggan.setText("Riwayat Transaksi Pelanggan");
        jMenuItemRiwayatTransasiPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRiwayatTransasiPelangganActionPerformed(evt);
            }
        });
        jMenuLaporan.add(jMenuItemRiwayatTransasiPelanggan);

        jMenuBar1.add(jMenuLaporan);

        jMenuMaster.setText("Master");
        jMenuMaster.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N

        jMenuItemDataKaryawan.setText("Data Karyawan");
        jMenuItemDataKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDataKaryawanActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemDataKaryawan);

        jMenuItemDataPelanggan.setText("Data Pelanggan");
        jMenuItemDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDataPelangganActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemDataPelanggan);

        jMenuItemDataPaket.setText("Data Paket");
        jMenuItemDataPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDataPaketActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemDataPaket);

        jMenuItemDataLayanan.setText("Data Layanan");
        jMenuItemDataLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDataLayananActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemDataLayanan);

        jMenuBar1.add(jMenuMaster);

        jMenuPengaturan.setText("Pengaturan");
        jMenuPengaturan.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N

        jMenuItemProfile.setText("Profile");
        jMenuItemProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfileActionPerformed(evt);
            }
        });
        jMenuPengaturan.add(jMenuItemProfile);

        jMenuItemGantiPassword.setText("Ganti Password");
        jMenuItemGantiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGantiPasswordActionPerformed(evt);
            }
        });
        jMenuPengaturan.add(jMenuItemGantiPassword);

        jMenuItemKeluar.setText("Keluar");
        jMenuItemKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKeluarActionPerformed(evt);
            }
        });
        jMenuPengaturan.add(jMenuItemKeluar);

        jMenuBar1.add(jMenuPengaturan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTransaksiBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransaksiBaruActionPerformed
        TransactionOrder transactionOrder = new TransactionOrder();
        transactionOrder.setVisible(true);
        transactionOrder.pack();
        transactionOrder.setLocationRelativeTo(null);
        transactionOrder.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemTransaksiBaruActionPerformed

    private void jMenuItemPembayaranTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPembayaranTransaksiActionPerformed
        TransactionPayment transactionPayment = new TransactionPayment();
        transactionPayment.setVisible(true);
        transactionPayment.pack();
        transactionPayment.setLocationRelativeTo(null);
        transactionPayment.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemPembayaranTransaksiActionPerformed

    private void jMenuItemTransaksiLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransaksiLayananActionPerformed
        TransactionService transactionService = new TransactionService();
        transactionService.setVisible(true);
        transactionService.pack();
        transactionService.setLocationRelativeTo(null);
        transactionService.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemTransaksiLayananActionPerformed

    private void jMenuItemTransaksiSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTransaksiSelesaiActionPerformed
        TransactionClose transactionClose = new TransactionClose();
        transactionClose.setVisible(true);
        transactionClose.pack();
        transactionClose.setLocationRelativeTo(null);
        transactionClose.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemTransaksiSelesaiActionPerformed

    private void jMenuItemLaporanPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLaporanPelangganActionPerformed
        ReportCustomer reportCustomer = new ReportCustomer();
        reportCustomer.setVisible(true);
        reportCustomer.pack();
        reportCustomer.setLocationRelativeTo(null);
        reportCustomer.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemLaporanPelangganActionPerformed

    private void jMenuItemLaporanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLaporanTransaksiActionPerformed
        ReportTransaction reportTransaction = new ReportTransaction();
        reportTransaction.setVisible(true);
        reportTransaction.pack();
        reportTransaction.setLocationRelativeTo(null);
        reportTransaction.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemLaporanTransaksiActionPerformed

    private void jMenuItemRiwayatTransasiPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRiwayatTransasiPelangganActionPerformed
        ReportHistoryTransaction reportHistoryTransaction = new ReportHistoryTransaction();
        reportHistoryTransaction.setVisible(true);
        reportHistoryTransaction.pack();
        reportHistoryTransaction.setLocationRelativeTo(null);
        reportHistoryTransaction.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemRiwayatTransasiPelangganActionPerformed

    private void jMenuItemDataKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDataKaryawanActionPerformed
        Employee employee = new Employee();
        employee.setVisible(true);
        employee.pack();
        employee.setLocationRelativeTo(null);
        employee.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemDataKaryawanActionPerformed

    private void jMenuItemDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDataPelangganActionPerformed
        Customer customer = new Customer();
        customer.setVisible(true);
        customer.pack();
        customer.setLocationRelativeTo(null);
        customer.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemDataPelangganActionPerformed

    private void jMenuItemDataPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDataPaketActionPerformed
        MasterPackage masterPackage = new MasterPackage();
        masterPackage.setVisible(true);
        masterPackage.pack();
        masterPackage.setLocationRelativeTo(null);
        masterPackage.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemDataPaketActionPerformed

    private void jMenuItemDataLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDataLayananActionPerformed
        MasterService service = new MasterService();
        service.setVisible(true);
        service.pack();
        service.setLocationRelativeTo(null);
        service.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemDataLayananActionPerformed

    private void jMenuItemProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfileActionPerformed
        Profile profile = new Profile();
        profile.setVisible(true);
        profile.pack();
        profile.setLocationRelativeTo(null);
        profile.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemProfileActionPerformed

    private void jMenuItemGantiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGantiPasswordActionPerformed
        ChangePassword changePassword = new ChangePassword();
        changePassword.setVisible(true);
        changePassword.pack();
        changePassword.setLocationRelativeTo(null);
        changePassword.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemGantiPasswordActionPerformed

    private void jMenuItemKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKeluarActionPerformed
        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        login.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_jMenuItemKeluarActionPerformed

    private void textKodePaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKodePaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKodePaketActionPerformed

    private void textNamaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaPaketActionPerformed

    private void textHargaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHargaPaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHargaPaketActionPerformed

    public boolean doValidate() {
        boolean valid = false;
        if (MyHelper.validateTextRequired(textNamaPaket)
                && MyHelper.validateTextRequired(textHargaPaket)
                && MyHelper.validateTextAreaRequired(textAreaKeterangan)) {
            valid = true;
        }

        return valid;
    }
    
    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        if (!doValidate()) {
            return;
        }
        try {
            String sql = "INSERT INTO MASTER_PACKAGE (PACKAGE_ID, PACKAGE_NAME, PACKAGE_PRICE, PACKAGE_DESCRIPTION) VALUES (?,?,?,?)";
            PreparedStatement stat = connection.prepareStatement(sql);
            stat.setString(1, textKodePaket.getText());
            stat.setString(2, textNamaPaket.getText());
            stat.setString(3, textHargaPaket.getText());
            stat.setString(4, textAreaKeterangan.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            doReset();
            textNamaPaket.requestFocus();
            dataTable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e.getMessage());
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        if (!doValidate()) {
            return;
        }
        try {
            String sql = "UPDATE MASTER_PACKAGE SET PACKAGE_NAME = ?, PACKAGE_PRICE = ?, PACKAGE_DESCRIPTION = ?"
            + " where PACKAGE_ID = ?";
            PreparedStatement stat = connection.prepareStatement(sql);

            stat.setString(1, textNamaPaket.getText());
            stat.setString(2, textHargaPaket.getText());
            stat.setString(3, textAreaKeterangan.getText());
            stat.setString(4, textKodePaket.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            doReset();
            textNamaPaket.requestFocus();
            dataTable();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal diubah" + e);
        }
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        try {
            String sqlDelete = "DELETE FROM MASTER_PACKAGE where PACKAGE_ID = ?";
            PreparedStatement statDelete = connection.prepareStatement(sqlDelete);
            statDelete.setString(1, textKodePaket.getText());
            statDelete.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            doReset();
            dataTable();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal dihapus" + e);
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        doReset();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void textKataKunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKataKunciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKataKunciActionPerformed

    private void tablePaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePaketMouseClicked
        int row = tablePaket.getSelectedRow();
        textKodePaket.setText(tablePaket.getValueAt(row, 0).toString());
        textNamaPaket.setText(tablePaket.getValueAt(row, 1).toString());
        textHargaPaket.setText(tablePaket.getValueAt(row, 2).toString());
        textAreaKeterangan.setText(tablePaket.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tablePaketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterPackage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterPackage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelHargaPaket;
    private javax.swing.JLabel jLabelKeterangan;
    private javax.swing.JLabel jLabelKodePaket;
    private javax.swing.JLabel jLabelNamaPaket;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemDataKaryawan;
    private javax.swing.JMenuItem jMenuItemDataLayanan;
    private javax.swing.JMenuItem jMenuItemDataPaket;
    private javax.swing.JMenuItem jMenuItemDataPelanggan;
    private javax.swing.JMenuItem jMenuItemGantiPassword;
    private javax.swing.JMenuItem jMenuItemKeluar;
    private javax.swing.JMenuItem jMenuItemLaporanPelanggan;
    private javax.swing.JMenuItem jMenuItemLaporanTransaksi;
    private javax.swing.JMenuItem jMenuItemPembayaranTransaksi;
    private javax.swing.JMenuItem jMenuItemProfile;
    private javax.swing.JMenuItem jMenuItemRiwayatTransasiPelanggan;
    private javax.swing.JMenuItem jMenuItemTransaksiBaru;
    private javax.swing.JMenuItem jMenuItemTransaksiLayanan;
    private javax.swing.JMenuItem jMenuItemTransaksiSelesai;
    private javax.swing.JMenu jMenuLaporan;
    private javax.swing.JMenu jMenuMaster;
    private javax.swing.JMenu jMenuPengaturan;
    private javax.swing.JMenu jMenuTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelKataKunci;
    private javax.swing.JTable tablePaket;
    private javax.swing.JTextArea textAreaKeterangan;
    private javax.swing.JTextField textHargaPaket;
    private javax.swing.JTextField textKataKunci;
    private javax.swing.JTextField textKodePaket;
    private javax.swing.JTextField textNamaPaket;
    // End of variables declaration//GEN-END:variables
}
